eureka:
    client:
        service-url:
            defaultZone: http://localhost:8762/eureka
    instance:
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
server:
    port: ${PORT:0}
spring:
    application:
        name: ms-registros
    cloud:
        loadbalancer:
            ribbon:
                enable: false
    data:
        mongodb:
            uri: mongodb://localhost:27017/db_ms_registros
