eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8091
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:4200'
            allowedHeaders:
              - Content-Type
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - filters: StripPrefix=2
          id: ms-productos
          predicates: Path=/api/productos/**
          uri: lb://ms-productos
        - filters: StripPrefix=2
          id: ms-facturas
          predicates: Path=/api/facturas/**
          uri: lb://ms-facturas
        - filters: StripPrefix=2
          id: ms-registros
          predicates: Path=/api/registros/**
          uri: lb://ms-registros

loadbalancer:
  ribbon:
    enable: false